apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: istio-system
spec:
  rules:
  - host: "www.service.com"
    http:
      paths:
      - path: "/"
        backend:
          service:
            name: istio-ingressgateway
            port: 
              number: 80

  - host: "tracing.service.com"
    http:
      paths:
      - path: "/"
        backend:
          service: 
            name: tracing
            port:
              number: 80


  - host: "grafana.service.com"
    http:
      paths:
      - path: "/"
        backend:
          service: 
            name: grafana
            port:
              number: 3000
